library(shiny)

app_dir <- normalizePath(".", winslash = "/", mustWork = TRUE)
project_root <- normalizePath(file.path(app_dir, "..", ".."), winslash = "/", mustWork = TRUE)

base_css_path <- file.path(project_root, "styles-base.css")
ai_css_path <- file.path(project_root, "styles-ai.css")
override_css_path <- file.path(app_dir, "generated", "style-overrides.css")

read_text_file <- function(path) {
  paste(readLines(path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
}

write_override_css <- function(css_text) {
  writeLines(css_text, override_css_path, useBytes = TRUE)
}

escape_attr <- function(x) {
  gsub('"', "&quot;", x, fixed = TRUE)
}

build_override_css <- function(v) {
  paste0(
    "/* Generated by codex/style-editor-prototype/app.R */\n",
    "/* Updated: ", format(Sys.time(), "%Y-%m-%d %H:%M:%S"), " */\n\n",
    ":root{\n",
    "  --accent: ", v$accent, ";\n",
    "  --accent-light: ", v$accent_light, ";\n",
    "  --accent-pink: ", v$accent_pink, ";\n",
    "  --accent-pink-strong: ", v$accent_pink_strong, ";\n",
    "  --yellow: ", v$yellow, ";\n",
    "  --yellow-light: ", v$yellow_light, ";\n",
    "  --light-grey: ", v$light_grey, ";\n",
    "  --normal-grey: ", v$normal_grey, ";\n",
    "  --page-bg: ", v$page_bg, ";\n",
    "  --black: ", v$black, ";\n",
    "}\n\n",
    ".intro-slide .pill{\n",
    "  font-size: ", v$intro_badge_size, "px;\n",
    "}\n\n",
    ".intro-slide .main{\n",
    "  font-size: ", v$intro_main_size, "px;\n",
    "}\n\n",
    ".intro-slide .subtitle{\n",
    "  font-size: ", v$intro_subtitle_size, "px;\n",
    "}\n\n",
    ".intro-slide .brand-logo,\n",
    ".intro-slide .brand-placeholder{\n",
    "  left: ", v$intro_logo_left, "px;\n",
    "  bottom: ", v$intro_logo_bottom, "px;\n",
    "}\n\n",
    ".agenda-slide{\n",
    "  padding: ", v$agenda_padding_y, "px ", v$agenda_padding_x, "px;\n",
    "}\n\n",
    ".agenda-title{\n",
    "  font-size: ", v$agenda_title_size, "px;\n",
    "}\n\n",
    ".agenda-list{\n",
    "  gap: ", v$agenda_list_gap, "px;\n",
    "}\n\n",
    ".agenda-item{\n",
    "  gap: ", v$agenda_item_gap, "px;\n",
    "}\n"
  )
}

preview_markup <- paste(
  '<div class="preview-shell">',
  '  <div class="preview-stage">',
  '    <div class="preview-canvas">',
  '      <div class="slide intro-slide">',
  '        <div class="top-badge"><span class="pill">Quick Scan</span></div>',
  '        <div class="main accent">Engagement pruzkum</div>',
  '        <div class="subtitle-wrap">',
  '          <div class="subtitle">Manazersky vystup</div>',
  '          <div class="reserved-logo-space" aria-hidden="true"></div>',
  '        </div>',
  '        <div class="brand-placeholder" aria-hidden="true">juiceUP</div>',
  '      </div>',
  '      <div class="slide agenda-slide">',
  '        <div class="agenda-content">',
  '          <div class="agenda-title">Co nas dnes ceka</div>',
  '          <ul class="agenda-list">',
  '            <li class="agenda-item"><span class="agenda-num">01</span><span class="agenda-text">Pruzkum v cislech</span></li>',
  '            <li class="agenda-item"><span class="agenda-num">02</span><span class="agenda-text">Vysledky engagementu</span></li>',
  '            <li class="agenda-item"><span class="agenda-num">03</span><span class="agenda-text">Vysledky jednotlivych driveru</span></li>',
  '            <li class="agenda-item"><span class="agenda-num">04</span><span class="agenda-text">Otazky, ktere dopadly hure</span></li>',
  '            <li class="agenda-item"><span class="agenda-num">05</span><span class="agenda-text">Multiple choice otazky</span></li>',
  '            <li class="agenda-item"><span class="agenda-num">06</span><span class="agenda-text">Otevrene otazky</span></li>',
  '            <li class="agenda-item"><span class="agenda-num">07</span><span class="agenda-text">Zaverecne shrnuti a doporuceni</span></li>',
  '          </ul>',
  '        </div>',
  '        <div class="progress-bar"></div>',
  '      </div>',
  '    </div>',
  '  </div>',
  '</div>',
  sep = "\n"
)

base_css <- read_text_file(base_css_path)
ai_css <- read_text_file(ai_css_path)

ui <- fluidPage(
  tags$head(
    tags$title("Survey Style Editor Prototype"),
    tags$style(HTML("
      body { background: #f4f4f1; }
      .app-title { margin: 0 0 6px 0; font-size: 28px; font-weight: 700; }
      .app-subtitle { margin: 0 0 18px 0; color: #4d4d4d; max-width: 900px; }
      .panel-block {
        background: #ffffff;
        border: 1px solid #dedbd2;
        border-radius: 14px;
        padding: 16px 18px;
        margin-bottom: 16px;
        box-shadow: 0 10px 30px rgba(0, 0, 0, 0.04);
      }
      .panel-block h3 {
        margin-top: 0;
        font-size: 18px;
      }
      .preview-shell {
        overflow: auto;
        background: linear-gradient(180deg, #ece9df 0%, #f8f6f1 100%);
        border-radius: 18px;
        padding: 18px;
      }
      .preview-stage {
        min-width: 700px;
      }
      .preview-canvas {
        transform: scale(0.33);
        transform-origin: top left;
        width: calc(1920px * 0.33);
        height: calc(2160px * 0.33);
      }
      .preview-canvas .slide + .slide {
        margin-top: 24px;
      }
      .brand-placeholder {
        position: absolute;
        left: 48px;
        bottom: 40px;
        height: 56px;
        min-width: 150px;
        padding: 10px 14px;
        display: flex;
        align-items: center;
        justify-content: center;
        border: 2px solid var(--black);
        font-family: var(--Europa-Bold);
        font-size: 24px;
        background: #fff;
      }
      .form-group { margin-bottom: 12px; }
      .help-note {
        font-size: 13px;
        color: #555;
        margin-top: 8px;
      }
      textarea.code-dump {
        font-family: Consolas, monospace;
      }
    "))
  ),
  fluidRow(
    column(
      width = 12,
      div(
        class = "panel-block",
        h1(class = "app-title", "Survey style editor prototype"),
        p(
          class = "app-subtitle",
          "This prototype only edits core tokens plus the intro and agenda slide layouts. It writes a generated override stylesheet so the hand-tuned source CSS stays intact."
        )
      )
    )
  ),
  fluidRow(
    column(
      width = 4,
      div(
        class = "panel-block",
        h3("Global tokens"),
        textInput("accent", "Accent", value = "#63e8c6"),
        textInput("accent_light", "Accent light", value = "#e1faf4"),
        textInput("accent_pink", "Accent pink", value = "#ff8ade"),
        textInput("accent_pink_strong", "Accent pink strong", value = "#ff67aa"),
        textInput("yellow", "Yellow", value = "#ffd06b"),
        textInput("yellow_light", "Yellow light", value = "#ffedc3"),
        textInput("light_grey", "Light grey", value = "#d1d1d1"),
        textInput("normal_grey", "Normal grey", value = "#a5a5a5"),
        textInput("page_bg", "Page background", value = "#ffffff"),
        textInput("black", "Black", value = "#000000")
      ),
      div(
        class = "panel-block",
        h3("Intro slide"),
        sliderInput("intro_badge_size", "Badge size", min = 24, max = 64, value = 36),
        sliderInput("intro_main_size", "Main title size", min = 96, max = 220, value = 160),
        sliderInput("intro_subtitle_size", "Subtitle size", min = 32, max = 96, value = 64),
        sliderInput("intro_logo_left", "Logo left", min = 0, max = 200, value = 48),
        sliderInput("intro_logo_bottom", "Logo bottom", min = 0, max = 200, value = 40)
      ),
      div(
        class = "panel-block",
        h3("Agenda slide"),
        sliderInput("agenda_padding_y", "Vertical padding", min = 80, max = 220, value = 140),
        sliderInput("agenda_padding_x", "Horizontal padding", min = 100, max = 260, value = 180),
        sliderInput("agenda_title_size", "Agenda title size", min = 48, max = 120, value = 80),
        sliderInput("agenda_list_gap", "List gap", min = 10, max = 60, value = 30),
        sliderInput("agenda_item_gap", "Item gap", min = 12, max = 60, value = 36),
        actionButton("reset_defaults", "Reset defaults")
      )
    ),
    column(
      width = 8,
      div(
        class = "panel-block",
        h3("Preview"),
        uiOutput("preview_ui"),
        p(
          class = "help-note",
          sprintf("Generated CSS is written to %s", override_css_path)
        )
      ),
      div(
        class = "panel-block",
        h3("Generated CSS"),
        tags$pre(
          class = "code-dump",
          style = "white-space: pre-wrap; min-height: 320px; margin: 0;",
          textOutput("css_text")
        )
      )
    )
  )
)

server <- function(input, output, session) {
  defaults <- list(
    accent = "#63e8c6",
    accent_light = "#e1faf4",
    accent_pink = "#ff8ade",
    accent_pink_strong = "#ff67aa",
    yellow = "#ffd06b",
    yellow_light = "#ffedc3",
    light_grey = "#d1d1d1",
    normal_grey = "#a5a5a5",
    page_bg = "#ffffff",
    black = "#000000",
    intro_badge_size = 36,
    intro_main_size = 160,
    intro_subtitle_size = 64,
    intro_logo_left = 48,
    intro_logo_bottom = 40,
    agenda_padding_y = 140,
    agenda_padding_x = 180,
    agenda_title_size = 80,
    agenda_list_gap = 30,
    agenda_item_gap = 36
  )

  observeEvent(input$reset_defaults, {
    for (nm in names(defaults)) {
      value <- defaults[[nm]]
      if (is.numeric(value)) {
        updateSliderInput(session, nm, value = value)
      } else {
        updateTextInput(session, nm, value = value)
      }
    }
  })

  override_css <- reactive({
    build_override_css(reactiveValuesToList(input))
  })

  observe({
    write_override_css(override_css())
  })

  output$preview_ui <- renderUI({
    tags$div(
      tags$style(HTML(base_css)),
      tags$style(HTML(ai_css)),
      tags$style(HTML(override_css())),
      HTML(preview_markup)
    )
  })

  output$css_text <- renderText({
    override_css()
  })
}

shinyApp(ui, server)
